app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from ..models.ua_models import ua_user

class LoginForm(FlaskForm):
    email = StringField('', validators=[DataRequired(), Length(1, 128), Email()])
    password = PasswordField('', validators=[DataRequired()])
    submit = SubmitField('登录')


class UserSettingForm(FlaskForm):
    email = StringField('', validators=[DataRequired(), Length(1, 128), Email()])
    mobile = StringField('', validators=[DataRequired(), Length(1, 64)])
    nick = StringField('', validators=[DataRequired(), Length(1, 64)])

class PasswordSettingForm(FlaskForm):
    password = PasswordField('', validators=[DataRequired()])
    new_password = PasswordField('', validators=[DataRequired()])
    rep_new_password = PasswordField('', validators=[DataRequired()])

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views, errors

app/user/views.py
import os
import time
import hashlib
from sqlalchemy import and_, or_
from functools import wraps
from datetime import datetime, timedelta
from flask import jsonify, render_template, redirect, url_for, abort, flash, request, current_app, make_response, Response
from flask_login import login_user, logout_user, login_required, current_user
from flask_moment import Moment
from . import user
from .forms import LoginForm, UserSettingForm, PasswordSettingForm
from .. import db
from ..models.ua_models import ua_user, User, SystemRole
from ..models.shop_models import shop_goods_classify, ShopPremission

def user_required(f):

    @wraps(f)
    def decorated_required(*args, **kargs):

        if current_user.is_authenticated and current_user.user.ua_user_system_role == SystemRole.CLIENT:

            return f(*args, **kargs)

        return redirect(url_for('user.login'))

    return decorated_required

def user_shop_permission_required(permission):

    def decorator(f):

        @wraps(f)
        def decorated_function(*args, **kargs):

            if current_user.user.ref_shop_user.first() and (current_user.user.ref_shop_user.first().shop_user_permission & permission) == permission:
                return f(*args, **kargs)

            return abort(403)

        return decorated_function

    return decorator


@user.before_app_request
def before_request():
    current_user

@user.route('/', methods=['GET'])
@user_required
def index():

    headimgurl = url_for('static', filename='images/user_blank_headimg.png')

    if current_user.user.ua_user_headimg and current_user.user.ua_user_headimg != '':
        headimgurl = current_user.user.ua_user_headimg

    return render_template('user/index.html', headimgurl=headimgurl)

@user.route('/login', methods=['GET', 'POST'])
def login():

    if not current_user.is_anonymous:
        return redirect(url_for('user.index'))

    form = LoginForm()

    if form.validate_on_submit():

        user = ua_user.query.filter_by(ua_user_email=form.email.data).first()

        if user is not None and user.verify_password(form.password.data) and user.ua_user_system_role == SystemRole.CLIENT:

            lguser = User(current_user.sess, user.ua_user_uuid)
            login_user(lguser, True)

            next = request.args.get('next')
            if next is None or not next.startswith('/'):
                next = url_for('user.index')

            return redirect(next)

        flash('账号或密码错误')

    return render_template('user/login.html', form=form)

@user.route('/logout')
@user_required
def logout():

    current_user.logout()
    logout_user()
    current_user.clear()

    flash('注销成功')
    return redirect(url_for('user.login'))

@user.route('/usersetting', methods=['GET', 'POST'])
@user_required
def usersetting():

    form = UserSettingForm()

    if form.validate_on_submit():

        user = current_user.user
        user.ua_user_email = form.email.data
        user.ua_user_moblie = form.mobile.data
        user.ua_user_nick = form.nick.data

        db.session.add(user)
        db.session.commit()

        flash('更新成功')

    headimgurl = url_for('static', filename='images/user_blank_headimg.png')
    
    if current_user.user.ua_user_headimg and current_user.user.ua_user_headimg != '':
        headimgurl = current_user.user.ua_user_headimg

    return render_template('user/usersetting.html', headimgurl=headimgurl, form=form)

@user.route('/uploadheadimage', methods=['POST'])
@user_required
def uploadheadimg():

    t = time.time()
    t = str(int(t))

    filename = current_user.user.ua_user_uuid + '_' + t

    hl = hashlib.md5()
    hl.update(filename.encode(encoding='utf-8'))
    filename = hl.hexdigest()

    
    with open(os.path.join(current_app.root_path, 'mediafile', 'headimage', filename + ".png"), 'wb') as fp:
        fp.write(request.data)

    user = current_user.user
    user.ua_user_headimg = url_for('user.getheadimage', filename=filename)

    db.session.add(user)
    db.session.commit()
    

    result = {
        'code': 200,
        'url': url_for('user.getheadimage', filename=filename)
    }

    return jsonify(result)

@user.route('/getheadimage/<string:filename>', methods=['GET'])
def getheadimage(filename):

    with open(os.path.join(current_app.root_path, 'mediafile', 'headimage', filename + ".png"), 'rb') as fp:
        data = fp.read()

    response = make_response(data)
    response.mimetype = "image/png"

    return response

@user.route('/passwordsetting', methods=['GET', 'POST'])
@user_required
def passwordsetting():

    form = PasswordSettingForm()

    if form.validate_on_submit():

        user = current_user.user
        
        if user is not None and user.verify_password(form.password.data):

            if form.new_password.data == form.rep_new_password.data:

                user.password = form.new_password.data
                db.session.add(user)
                db.session.commit()

                flash('更新成功')
            else:
                flash('密码不一致')
        else:
            flash('密码错误')

    headimgurl = url_for('static', filename='images/user_blank_headimg.png')
    
    if current_user.user.ua_user_headimg and current_user.user.ua_user_headimg != '':
        headimgurl = current_user.user.ua_user_headimg

    return render_template('user/passwordsetting.html', headimgurl=headimgurl, form=form)

@user.route('/shopgoodsclassifymanager', methods=['GET'])
@user.route('/shopgoodsclassifymanager/<string:puuid>', methods=['GET'])
@user_required
@user_shop_permission_required(ShopPremission.MANAGERGOODS)
def shopgoodsclassifymanager(puuid='0'):

    headimgurl = url_for('static', filename='images/user_blank_headimg.png')
    
    if current_user.user.ua_user_headimg and current_user.user.ua_user_headimg != '':
        headimgurl = current_user.user.ua_user_headimg

    ppuuid = '0'

    ppclassify = shop_goods_classify.query.filter(and_(shop_goods_classify.shop_goods_classify_uuid == puuid, shop_goods_classify.shop_basic_uuid == current_user.user.ref_shop_user.first().shop_basic_uuid)).first()

    if ppclassify:
        ppuuid = ppclassify.shop_goods_classify_puuid

    return render_template('user/shopgoodsclassifymanager.html', headimgurl=headimgurl, pid=puuid, ppid=ppuuid)


@user.route('/addshopgoodsclassify', methods=['GET', 'POST'])
@user_required
@user_shop_permission_required(ShopPremission.MANAGERGOODS)
def addshopgoodsclassify():

    result = {
        'code': 500,
    }

    name = request.form['name']
    puuid = request.form['pid'] if 'pid' in request.form.keys() else '0'

    if name and puuid:

        classify = shop_goods_classify(
            shop_goods_classify_puuid=puuid, 
            shop_goods_classify_name=name,
            shop_basic_uuid=current_user.user.ref_shop_user.first().shop_basic_uuid)

        db.session.add(classify)
        db.session.commit()

        result["code"] = 200


    return jsonify(result)

@user.route('/delshopgoodsclassify', methods=['GET', 'POST'])
@user_required
@user_shop_permission_required(ShopPremission.MANAGERGOODS)
def delshopgoodsclassify():
    result = {
        'code': 500,
    }

    uuid = request.form['uuid']

    if uuid:

        classify = shop_goods_classify.query.filter(and_(shop_goods_classify.shop_goods_classify_uuid == uuid, shop_goods_classify.shop_basic_uuid == current_user.user.ref_shop_user.first().shop_basic_uuid)).first()

        if classify:

            db.session.delete(classify)
            db.session.commit()

        result["code"] = 200


    return jsonify(result)


@user.route('/editshopgoodsclassify', methods=['GET', 'POST'])
@user_required
@user_shop_permission_required(ShopPremission.MANAGERGOODS)
def editshopgoodsclassify():
    result = {
        'code': 500,
    }

    uuid = request.form['uuid']

    if uuid:

        classify = shop_goods_classify.query.filter(and_(shop_goods_classify.shop_goods_classify_uuid == uuid, shop_goods_classify.shop_basic_uuid == current_user.user.ref_shop_user.first().shop_basic_uuid)).first()

        if classify:

            if 'name' in request.form:
                classify.shop_goods_classify_name = request.form['name']

            db.session.add(classify)
            db.session.commit()

        result["code"] = 200


    return jsonify(result)

@user.route('/getshopgoodsclassify', methods=['GET', 'POST'])
@user.route('/getshopgoodsclassify/<string:puuid>', methods=['GET', 'POST'])
@user_required
@user_shop_permission_required(ShopPremission.MANAGERGOODS)
def getshopgoodsclassify(puuid='0'):

    limit = int(request.form['limit']) if 'limit' in request.form.keys() else 10
    start = int(request.form['start']) if 'start' in request.form.keys() else 0
    page = int(request.form['page']) if 'page' in request.form.keys() else 1
    draw = int(request.form['draw']) if 'draw' in request.form.keys() else 1
    keyword = request.form['keyword'] if 'keyword' in request.form.keys() else None

    classify = shop_goods_classify.query

    classify = classify.filter(and_(shop_goods_classify.shop_goods_classify_puuid == puuid, shop_goods_classify.shop_basic_uuid == current_user.user.ref_shop_user.first().shop_basic_uuid))

    if keyword:
        rule = or_(shop_goods_classify.shop_goods_classify_name.like(f'%{keyword}%'))
        classify = classify.filter(rule)
    else:
        pass

    total = classify.count()
    classify = classify.order_by(shop_goods_classify.shop_goods_classify_createtime.asc()).limit(limit).offset(start).all()
    classifylist = []

    for item in classify:
        data = {
            'uuid': item.shop_goods_classify_uuid,
            'name': item.shop_goods_classify_name,
        }
        classifylist.append(data)

    result = {
        'code': 200,
        'draw': draw,
        'total': total,
        'data': classifylist
    }

    return jsonify(result)

'''

@manager.route('/usermanager', methods=['GET'])
@manager_required
def usermanager():

app/templates/user/base_user.html
{% extends "user/base.html" %}

{% block title %}Liteshop Manager{% endblock %}

{% block styles %}
{{ super() }}
<link href="{{ url_for('static', filename='css/user.css') }}" rel="stylesheet">
{% endblock %}

{% block body_attribs %} class="nav-md"{% endblock %}


{% block content %}

<div class="container body">
	<div class="main_container">
		<div class="col-md-3 left_col menu_fixed">
			<div class="left_col scroll-view">
				<div class="navbar nav_title" style="border: 0;">
		    		<a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>店铺管理</span></a>
		    	</div>

		    	<div class="clearfix"></div>

		    	<!-- menu profile quick info -->
		    	<!--
		    	<div class="profile clearfix">
		      		<div class="profile_pic">
		        		<img src="{{ headimgurl }}" alt="" class="img-circle profile_img">
		      		</div>
		      		<div class="profile_info">
		        		<span>你好,</span>
		        		<h2>{{ current_user.user.ua_user_nick }}</h2>
		      		</div>
		    	</div>
		    	-->
		    	<!-- /menu profile quick info -->

		    	<br />

		    	<!-- sidebar menu -->
		    	<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
		    		<div class="menu_section">
		        		<!-- <h3>通用</h3> -->
		        		<ul class="nav side-menu">
			          		<li>
			          			<a href="{{ url_for('user.index') }}"><i class="fa fa-home"></i>首页</a>
			          		</li>
							<li>
								<a href="{{ url_for('user.shopgoodsclassifymanager') }}"><i class="fa fa-sitemap"></i>店铺分类</a>
							</li>
							<li>
								<a href="{{ url_for('manager.usermanager') }}"><i class="fa fa-user"></i>店铺用户</a>
							</li>
						</ul>
					</div>
		    	</div>
		    	<!-- /sidebar menu -->

		  		<!-- /menu footer buttons -->
		    	<div class="sidebar-footer hidden-small">
		    		<a href="#" data-toggle="tooltip" data-placement="top" title="返回顶部">
		        		<span class="glyphicon glyphicon-circle-arrow-up" aria-hidden="true"></span>
		    		</a>
		    		<a href="{{ url_for('user.usersetting') }}" data-toggle="tooltip" data-placement="top" title="个人资料">
		        		<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
		    		</a>
		    		<a href="{{ url_for('user.passwordsetting') }}" data-toggle="tooltip" data-placement="top" title="修改密码">
		        		<span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
		    		</a>
		    		<a href="{{ url_for('user.logout') }}" data-toggle="tooltip" data-placement="top" title="注销" href="login.html">
		        		<span class="glyphicon glyphicon-off" aria-hidden="true"></span>
		    		</a>
		    	</div>
		    	<!-- /menu footer buttons -->
			</div>
		</div>

        <!-- top navigation -->
        <div class="top_nav">
			<div class="nav_menu">
				<nav>
					<div class="nav toggle">
				  		<a id="menu_toggle"><i class="fa fa-bars"></i></a>
				  	</div>

					<ul class="nav navbar-nav navbar-right">
						<li class="">
				    		<a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
				        		<img src="{{ headimgurl }}" alt="">{{ current_user.user.ua_user_nick }}
				        		<span class="fa fa-angle-down"></span>
				      		</a>

				    		<ul class="dropdown-menu dropdown-usermenu pull-right">
				    			<li><a href="{{ url_for('user.passwordsetting') }}">修改密码</a></li>
				        		<li><a href="{{ url_for('user.usersetting') }}">个人资料</a></li>
				        		<li><a href="{{ url_for('user.logout') }}"><i class="fa fa-sign-out pull-right"></i>注销</a></li>
				    		</ul>
				    	</li>
					</ul>
				</nav>
			</div>
        </div>
        <!-- /top navigation -->
        <div class="right_col" role="main" style="overflow: hidden;">

		{% for message in get_flashed_messages() %}
		<div class="alert alert-warning" style="margin: 6px 6px;position: relative;z-index: 99;">
		    <button type="button" class="close" data-dismiss="alert" style="position: absolute;top: 50%;margin-top: -10.5px;right: 15px;">&times;</button>
		    {{ message }}
		</div>
		{% endfor %}

        {% block page_content %}
        {% endblock page_content %}
    	</div>

		{% block footer %}
		<footer>
		    <div class="pull-right">
		        Shop User
		    </div>
		    <div class="clearfix"></div>
		</footer>
		{% endblock %}
	</div>
</div>



{% endblock %}

app/templates/user/index.html
{% extends "user/base_user.html" %}

app/templates/user/login.html
{% extends "user/base.html" %}

{% block title %}Liteshop{% endblock title %}

{% block body_attribs %} class="login"{% endblock %}


{% block content %}

{% for message in get_flashed_messages() %}
<div class="alert alert-warning" style="margin: 6px 6px;position: relative;z-index: 99;">
    <button type="button" class="close" data-dismiss="alert" style="position: absolute;top: 50%;margin-top: -10.5px;right: 15px;">&times;</button>
    {{ message }}
</div>
{% endfor %}


<div>
    <div class="login_wrapper">
        <div class="animate form login_form">
            <section class="login_content">
                <form action="{{ url_for('user.login') }}" method="post">
                    {{form.csrf_token}}
                    <h1>用户登录</h1>
                    <div>
                        <input type="text" class="form-control" name="email" value="" placeholder="用户名/电子邮箱"/>
                    </div>
                    <div>
                        <input type="password" class="form-control" name="password" value="" placeholder="密码"/>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-default submit">登录</button>
                    </div>

                    <div class="clearfix"></div>

                    <div class="separator">

                        <div class="clearfix"></div>
                        <br />

                        <div>
                            <h1><i class="fa fa-paw"></i> LiteShop</h1>
                            <p>©2019 All Rights Reserved.</p>
                        </div>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>
{% endblock %}

app/templates/user/passwordsetting.html
{% extends "user/base_user.html" %}

{% block page_content %}
<div class="col-md-12 col-sm-12 col-xs-12">
	<div class="x_panel">
		<div class="x_title">
			<h2>登录密码 <small>修改</small></h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
        	<br />
            <div class="ln_solid"></div>
        	<form id="setting-form" data-parsley-validate class="form-horizontal form-label-left" action="{{ url_for('user.passwordsetting') }}" method="post">
        		{{form.csrf_token}}
            	<div class="form-group">
                	<label class="control-label col-md-1 col-sm-1 col-xs-12" for="user_email">原始密码<span class="required">*</span></label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                    	<input type="password" name="password" id="user_email" value="" required="required" class="form-control col-md-7 col-xs-12">
                    </div>
                </div>
                <div class="form-group">
                	<label class="control-label col-md-1 col-sm-1 col-xs-12" for="user_mobile">新密码<span class="required">*</span></label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                    	<input type="password" name="new_password" id="user_mobile" value="" required="required" class="form-control col-md-7 col-xs-12">
                    </div>
                </div>
                <div class="form-group">
                	<label class="control-label col-md-1 col-sm-1 col-xs-12" for="user_nick">重复密码<span class="required">*</span></label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                    	<input type="password" name="rep_new_password" id="user_nick" value="" required="required" class="form-control col-md-7 col-xs-12">
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                	<div class="col-md-12 col-sm-12 col-xs-12">
                		<button class="btn btn-primary" type="button" onclick="cancel()">取消</button>
                		<script type="text/javascript">
                			function cancel () {
                				window.location.href = "{{url_for('user.index')}}"
                			}
                		</script>
                		<button type="submit" class="btn btn-success">提交</button>
                	</div>
            	</div>

        	</form>
    	</div>
	</div>
</div>
{% endblock page_content %}

app/templates/user/usersetting.html
{% extends "user/base_user.html" %}

{% block page_content %}
<div class="col-md-12 col-sm-12 col-xs-12">
	<div class="x_panel">
		<div class="x_title">
			<h2>个人资料 <small>设置与修改</small></h2>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
        	<br />
        	<div id="setting-top">
        		<div id="headimg-group" class="col-md-3 col-sm-3 col-xs-6">
	            	<img class="img-responsive avatar-view" src="{{ headimgurl }}" alt="">
	            	<button id="updateheadimg" type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target=".bs-modal-update-headimg">修改头像</button>
	            	<!-- modals -->
                  	<div class="modal fade bs-modal-update-headimg" tabindex="-1" role="dialog" aria-hidden="true">
                    	<div class="modal-dialog modal-lg">
                      		<div class="modal-content">

                        		<div class="modal-header">
                          			<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span></button>
                          			<h4 class="modal-title">修改头像</h4>
                        		</div>
                        		<div class="modal-body">
		                        	<div id="upload_zone">
                                        <div class="uz-message">
                                            <span>点击或拖动文件到此区域</span>
                                        </div>
                                        <input id="file_headimg_upload" accept="image/*" type="file" title=""/>
                                    </div>
                                    <div id="cropper_box">
                                        
                                    </div>
                                    <div id="upload_progress">
                                        <div class="up-message">
                                            <span class="glyphicon glyphicon-repeat" aria-hidden="true"></span>
                                            <span style="font-size: 18px;">上传中...</span>
                                        </div>
                                    </div>
                                    
                        		</div>
                        		<div class="modal-footer">
                          			<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                          			<button id="cropper_confirm" type="button" class="btn btn-primary">确认</button>
                        		</div>
                                <script type="text/javascript">
                                    $('#file_headimg_upload').bind('change', function () {
                                        var obj = this;
                                                            
                                        if (obj.files) {

                                            for (var i = 0; i < obj.files.length; i++) {

                                                var fr = new FileReader();

                                                fr.onload = (function (file, evt) {

                                                    return function (evt) {

                                                        initcropper(file, this.result)
                                                    }

                                                })(obj.files[i]);

                                                fr.readAsDataURL(obj.files[i]);
                                            }

                                        }

                                    });

                                    function initcropper (file, base64code) {
                                        $("#upload_zone").hide();
                                        $("#cropper_box").show();

                                        var img = new Image();

                                        img.onload = function () {
                                            $("#cropper_box").append(img);

                                            $cropperimg = $('#cropper_box img')

                                            $cropperimg.cropper({
                                                aspectRatio: 1 / 1,
                                                viewMode: 1,
                                                autoCropArea: 1,
                                                crop: function (e) {
                                                    //console.log(e);
                                                }
                                            });
                                        };

                                        img.src = base64code;

                                    }

                                    $('#cropper_confirm').bind('click', function () {

                                        if (typeof(issubmit) == 'undefined' || !issubmit) {

                                            if ($cropperimg) {

                                                var data = $cropperimg.cropper('getCroppedCanvas');

                                                data.toBlob(function (blob) {
                                                    $('#cropper_box').hide();
                                                    $('#upload_progress').show();
                                                    issubmit = true;
                                                    upload_file(blob)

                                                });
                                            }

                                        }

                                    });

                                    function upload_file(blob) {

                                        var xhr = new XMLHttpRequest();

                                        xhr.upload.addEventListener('progress', function(evt) {
                                            if (evt.lengthComputable) {
                                                var percentComplete = parseInt(evt.loaded / evt.total * 100);
                                            }

                                        }, false);

                                        xhr.addEventListener('load', function(evt) {

                                            if (evt.currentTarget.status == 200) {

                                                var result = $.parseJSON(evt.currentTarget.responseText);

                                                if (result.code == 200) {
                                                    var img = new Image();

                                                    img.onload = function () {
                                                        $('#headimg-group img').attr('src', this.src);
                                                        $('nav .user-profile img').attr('src', this.src);
                                                    };

                                                    img.src = result.url;
                                                }


                                                

                                                
                                            }

                                            destoryuploadheadimg();
                                            
                                        }, false);

                                        xhr.addEventListener('error', function (evt) {

                                            destoryuploadheadimg();
                                            
                                        }, false);

                                        xhr.addEventListener('abort', function () {

                                            destoryuploadheadimg();
                                            
                                        }, false);

                                        // 开始上传
                                        xhr.open('POST', '/user/uploadheadimage', true);
                                        xhr.send(blob);  
                                        
                                    }

                                    function destoryuploadheadimg () {

                                        $('#file_headimg_upload').val('');
                                        $('#cropper_box img').cropper('destroy');
                                        $("#cropper_box").empty();

                                        $("#upload_zone").show();
                                        $("#cropper_box").hide();
                                        $("#upload_progress").hide();
                                        $('.bs-modal-update-headimg').modal('hide');

                                        $cropperimg = null;
                                        issubmit = false;

                                    }

                                    /*
                                    $('.bs-modal-update-headimg').on('hidden.bs.modal', function () {
                                        $('.bs-modal-update-headimg-preview').modal('show')
                                    })
                                    */
                                </script>

                    		</div>
                    	</div>
                	</div>
	            </div>
            </div>
            <div class="ln_solid"></div>
        	<form id="setting-form" data-parsley-validate class="form-horizontal form-label-left" action="{{ url_for('user.usersetting') }}" method="post">
        		{{form.csrf_token}}
            	<div class="form-group">
                	<label class="control-label col-md-1 col-sm-1 col-xs-12" for="user_email">邮箱<span class="required">*</span></label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                    	<input type="text" name="email" id="user_email" value="{{ current_user.user.ua_user_email }}" required="required" class="form-control col-md-7 col-xs-12">
                    </div>
                </div>
                <div class="form-group">
                	<label class="control-label col-md-1 col-sm-1 col-xs-12" for="user_mobile">手机<span class="required">*</span></label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                    	<input type="text" name="mobile" id="user_mobile" value="{{ current_user.user.ua_user_moblie }}" required="required" class="form-control col-md-7 col-xs-12">
                    </div>
                </div>
                <div class="form-group">
                	<label class="control-label col-md-1 col-sm-1 col-xs-12" for="user_nick">昵称<span class="required">*</span></label>
                    <div class="col-md-10 col-sm-10 col-xs-12">
                    	<input type="text" name="nick" id="user_nick" value="{{ current_user.user.ua_user_nick }}" required="required" class="form-control col-md-7 col-xs-12">
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                	<div class="col-md-12 col-sm-12 col-xs-12">
                		<button class="btn btn-primary" type="button" onclick="cancel()">取消</button>
                		<script type="text/javascript">
                			function cancel () {
                				window.location.href = "{{url_for('user.index')}}"
                			}
                		</script>
                		<button type="submit" class="btn btn-success">提交</button>
                	</div>
            	</div>

        	</form>
    	</div>
	</div>
</div>
{% endblock page_content %}